# Generated by Django 3.1.12 on 2021-06-23 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        migrations.swappable_dependency(settings.OPENWISP_IPAM_IPADDRESS_MODEL),
        migrations.swappable_dependency(settings.OPENWISP_IPAM_SUBNET_MODEL),
        ('subnet_division', '0002_default_group_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnetdivisionindex',
            name='config',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.CONFIG_CONFIG_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='subnetdivisionindex',
            name='ip',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OPENWISP_IPAM_IPADDRESS_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='subnetdivisionindex',
            name='subnet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OPENWISP_IPAM_SUBNET_MODEL,
            ),
        ),
    ]
