# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 18:41
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('config', '0006_config_device_not_null')]

    operations = [
        migrations.RemoveField(model_name='config', name='name'),
        migrations.RemoveField(model_name='config', name='key'),
        migrations.RemoveField(model_name='config', name='mac_address'),
    ]
