# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 16:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('config', '0008_update_indexes')]

    operations = [
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='system on chip or CPU info',
                max_length=128,
                verbose_name='SOC / CPU',
            ),
        )
    ]
