# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 02:09
import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('config', '0010_auto_20180106_1814')]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(
                db_index=True,
                help_text='primary mac address',
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})', 32),
                        code='invalid',
                        message='Must be a valid mac address.',
                    )
                ],
            ),
        )
    ]
