# Generated by Django 2.0.8 on 2018-09-26 11:26

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_last_ip_management_ip_and_status_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='device',
            name='management_ip',
        ),
        migrations.AddField(
            model_name='config',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, help_text='indicates the last ip from which the configuration was downloaded from (except downloads from this page)', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='modified', help_text='modified means the configuration is not applied yet; running means applied and running; error means the configuration caused issues and it was rolledback', max_length=100, no_check_for_status=True),
        ),
    ]
