# Generated by Django 2.0.9 on 2018-12-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_default_organization_config_settings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template', unique_together={('organization', 'name')}
        )
    ]
