# Generated by Django 2.1.4 on 2019-01-09 01:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_template_name_organization_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='context',
            field=jsonfield.fields.JSONField(blank=True, help_text='Additional <a href="http://netjsonconfig.openwisp.org/en/stable/general/basics.html#context" target="_blank">context (configuration variables)</a> in JSON format', null=True),
        ),
    ]
