# Generated by Django 2.0.10 on 2019-02-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_organization_mac_add_hardware_id_name_unique_together')
    ]

    operations = [migrations.RemoveField(model_name='config', name='organization')]
