# Generated by Django 2.1.8 on 2019-04-22 23:55

import django.core.validators
from django.db import migrations, models
import django_netjsonconfig.utils
import re


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_remove_config_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='key',
            field=models.CharField(db_index=True, default=django_netjsonconfig.utils.get_random_key, max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[^\\s/\\.]+$'), code='invalid', message='Key must not contain spaces, dots or slashes.')]),
        ),
    ]
