# Generated by Django 3.0.3 on 2020-02-26 19:58

import collections

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("config", "0022_vpn_format_dh")]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="context",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=dict,
                dump_kwargs={"ensure_ascii": False, "indent": 4},
                help_text=(
                    "allows overriding "
                    '<a href="https://openwisp.io/docs/stable/controller/user/variables.html'  # noqa: E501
                    '" target="_blank">'
                    "configuration variables</a>"
                ),
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
            ),
        )
    ]
