# Generated by Django 3.0.3 on 2020-03-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_update_device_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(blank=True, help_text='Serial number of this device', max_length=32, null=True, verbose_name='Serial number'),
        ),
    ]
