# Generated by Django 3.0.3 on 2020-03-13 23:45

from django.db import migrations, models

from openwisp_controller.config import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [('config', '0025_update_device_key')]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(**app_settings.HARDWARE_ID_OPTIONS),
        )
    ]
