# Generated by Django 3.0.3 on 2020-06-29 23:54


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("config", "0027_add_indexes_on_ip_fields")]

    operations = [
        migrations.AddField(
            model_name="template",
            name="default_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Define default values for the variables used in this template. "
                    "These values are used during validation and when a variable is "
                    "not provided by the device, group, or organization."
                ),
                verbose_name="Default Values",
            ),
        )
    ]
