# Generated by Django 3.0.3 on 2020-06-29 23:54

import collections

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("config", "0027_add_indexes_on_ip_fields")]

    operations = [
        migrations.AddField(
            model_name="template",
            name="default_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "A dictionary containing the default values for "
                    "the variables used by this template; these default "
                    "variables will be used during schema validation."
                ),
                verbose_name="Default Values",
            ),
        )
    ]
