# Generated by Django 3.1.2 on 2020-10-07 20:34

from django.db import migrations

from .. import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_update_legacy_vpn_backend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={
                'verbose_name': app_settings.DEVICE_VERBOSE_NAME[0],
                'verbose_name_plural': app_settings.DEVICE_VERBOSE_NAME[1],
            },
        ),
    ]
