# Generated by Django 3.1.6 on 2021-02-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_update_legacy_vpn_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='vpn', unique_together={('organization', 'name')}
        ),
    ]
