# Generated by Django 3.1.8 on 2021-05-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_template_required'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={
                ('mac_address', 'organization'),
                ('hardware_id', 'organization'),
            },
        ),
    ]
