# Generated by Django 3.1.8 on 2021-04-23 22:17

from django.conf import settings
from django.db import migrations

import openwisp_controller.config.sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_template_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='templates',
            field=openwisp_controller.config.sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text='configuration templates, applied from first to last',
                related_name='config_relations',
                to=settings.CONFIG_TEMPLATE_MODEL,
                verbose_name='templates',
            ),
        ),
    ]
