# Generated by Django 3.1.13 on 2021-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_device_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='use_custom_ip',
            field=models.BooleanField(
                default=False,
                help_text='if enabled, user shall be able to change the '
                'management ip of the device manually',
            ),
        ),
    ]
