# Generated by Django 3.1.7 on 2021-03-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OPENWISP_IPAM_SUBNET_MODEL),
        ('config', '0037_alter_taggedtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='subnet',
            field=models.ForeignKey(
                blank=True,
                help_text='Subnet IP addresses used by VPN clients, if applicable',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.OPENWISP_IPAM_SUBNET_MODEL,
                verbose_name='Subnet',
            ),
        ),
    ]
