# Generated by Django 4.0.5 on 2022-06-21 17:49

from django.db import migrations

from . import assign_organization_config_settings_permissions_to_groups


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_vpnclient_ip_setnull'),
    ]

    operations = [
        migrations.RunPython(
            code=assign_organization_config_settings_permissions_to_groups,
            reverse_code=migrations.operations.special.RunPython.noop,
        )
    ]
