# Generated by Django 4.0.4 on 2022-05-05 06:44

from django.conf import settings
from django.db import migrations

import openwisp_controller.config.sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_vpnclient_ip_setnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='templates',
            field=openwisp_controller.config.sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=(
                    'Templates assigned to the devices which are part '
                    'of the group. Default and required templates are '
                    'excluded from this list. If the group on the device '
                    'is changed, these templates are automatically removed '
                    'and the templates of the new group are assigned.'
                ),
                related_name='device_group_relations',
                to=settings.CONFIG_TEMPLATE_MODEL,
                verbose_name='templates',
            ),
        ),
    ]
