# Generated by Django 4.0.3 on 2022-07-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0043_devicegroup_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='error_reason',
            field=models.CharField(
                blank=True,
                help_text='Error reason reported by the device',
                max_length=1024,
                verbose_name='error reason',
            ),
        ),
    ]
