# Generated by Django 3.2.15 on 2022-09-16 11:45

import django.db.models.deletion
import swapper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0045_alter_vpn_webhook_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLimits',
            fields=[
                (
                    'device_limit',
                    models.BigIntegerField(
                        default=0,
                        null=True,
                        blank=True,
                        verbose_name='device limit',
                        help_text=(
                            'Maximum number of devices allowed for this organization.'
                            ' "0" means unlimited.'
                        ),
                    ),
                ),
                (
                    'organization',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        related_name='config_limits',
                        to=swapper.get_model_name('openwisp_users', 'organization'),
                        verbose_name='organization',
                    ),
                ),
            ],
            options={
                'verbose_name': 'controller limits',
                'verbose_name_plural': 'controller limits',
                'abstract': False,
                'swappable': 'CONFIG_ORGANIZATIONLIMITS_MODEL',
            },
        ),
    ]
