# Generated by Django 3.2.15 on 2022-09-16 11:45


from django.db import migrations

from . import populate_organization_allowed_device


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0046_organizationlimits'),
    ]

    operations = [
        migrations.RunPython(
            populate_organization_allowed_device, migrations.RunPython.noop
        )
    ]
