# Generated by Django 3.2.18 on 2023-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_add_organizationlimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='auth_token',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Authentication token used for triggering '
                    '"Webhook Endpoint" or for calling "ZerotierService" API'
                ),
                max_length=128,
                null=True,
                verbose_name='Webhook AuthToken',
            ),
        ),
    ]
