# Generated by Django 3.2.19 on 2023-06-27 14:45

import collections

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0048_wifi_radio_band_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicegroup",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "This field can be used to add meta data for the group"
                    ' or to add "Configuration Variables" to the devices.'
                ),
                verbose_name="Configuration Variables",
            ),
        ),
    ]
