# Generated by Django 4.2.3 on 2023-07-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0049_devicegroup_context"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vpnclient",
            unique_together={("config", "vpn")},
        ),
    ]
