# Generated by Django 3.2.20 on 2023-07-22 10:49


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0050_alter_vpnclient_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Define reusable configuration variables available "
                    "to all devices in this organization"
                ),
                verbose_name="Configuration Variables",
            ),
        ),
    ]
