# Generated by Django 3.2.20 on 2023-07-22 10:49

import collections

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0050_alter_vpnclient_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    'This field can be used to add "Configuration Variables"'
                    " to the devices."
                ),
                verbose_name="Configuration Variables",
            ),
        ),
    ]
