# Generated by Django 3.2.19 on 2023-07-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_vpn_node_network_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnclient',
            name='member_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='zt_identity_secret',
            field=models.CharField(blank=True, max_length=44),
        ),
    ]
