# Generated by Django 3.2.20 on 2024-02-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0053_vpnclient_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='_is_deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
