# Generated by Django 4.2.18 on 2025-03-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0055_alter_config_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vpnclient",
            name="template",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.CONFIG_TEMPLATE_MODEL,
            ),
        ),
    ]
