# Generated by Django 4.2.18 on 2025-03-18 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0057_populate_vpnclient_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vpnclient",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.CONFIG_TEMPLATE_MODEL,
            ),
        ),
    ]
