# Generated by Django 5.2.1 on 2025-05-23 18:00

import uuid

import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import openwisp_utils.fields

from .. import settings as app_settings


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0059_zerotier_templates_ow_zt_to_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoIsInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(db_index=True),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, help_text="Organization name", max_length=200
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country Code", max_length=4
                    ),
                ),
                (
                    "asn",
                    models.CharField(
                        blank=True, help_text="Autonomous System Number", max_length=100
                    ),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, help_text="Time zone", max_length=100),
                ),
                (
                    "address",
                    jsonfield.fields.JSONField(
                        blank=True, default=dict, help_text="Address"
                    ),
                ),
                ("cidr", models.CharField(blank=True, help_text="CIDR", max_length=20)),
                (
                    "device",
                    models.OneToOneField(
                        help_text="Device to which this WhoIs info belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whois_info",
                        to=settings.CONFIG_DEVICE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "CONFIG_WhoIsINFO_MODEL",
            },
        ),
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="whois_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=app_settings.WHOIS_ENABLED,
                help_text="Whether WhoIs details lookup is enabled",
                null=True,
                verbose_name="WhoIs Enabled",
            ),
        ),
    ]
