# Generated by Django 5.2.1 on 2025-05-23 18:00

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0059_zerotier_templates_ow_zt_to_global"),
    ]

    operations = [
        migrations.CreateModel(
            name="WHOISInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "last_public_ip",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text=(
                            "indicates the IP address logged from "
                            "the last request coming from the device"
                        ),
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, help_text="Organization name", max_length=200
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Country Code", max_length=4
                    ),
                ),
                (
                    "asn",
                    models.CharField(
                        blank=True, help_text="Autonomous System Number", max_length=100
                    ),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, help_text="Time zone", max_length=100),
                ),
                (
                    "address",
                    models.CharField(blank=True, help_text="Address", max_length=255),
                ),
                ("cidr", models.CharField(blank=True, help_text="CIDR", max_length=20)),
                (
                    "device",
                    models.OneToOneField(
                        help_text="Device to which this WHOIS info belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whois_info",
                        to=settings.CONFIG_DEVICE_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "CONFIG_WHOISINFO_MODEL",
            },
        ),
    ]
