# Generated by Django for issue #1113 optimization

import hashlib
import json
from collections import OrderedDict
from copy import deepcopy

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
from django.db.models import Prefetch
from django.utils.module_loading import import_string

from openwisp_controller.config import settings as app_settings


def _pk_hex(obj):
    pk = obj.pk
    return pk.hex if hasattr(pk, "hex") else str(pk).replace("-", "")


def _normalize_json(value, default=None):
    default = {} if default is None else default
    if isinstance(value, str):
        try:
            value = json.loads(value) if value else deepcopy(default)
        except ValueError:
            value = deepcopy(default)
    return value if isinstance(value, type(default)) else deepcopy(default)


def _is_backend_type(obj, backend_type):
    return backend_type.lower() in obj.backend.lower()


def _first_dict(value):
    if not isinstance(value, list) or not value or not isinstance(value[0], dict):
        return {}
    return value[0]


def _auto_context_keys(vpn):
    pk = _pk_hex(vpn)
    context_keys = {
        "vpn_host": "vpn_host_{}".format(pk),
        "vpn_port": "vpn_port_{}".format(pk),
    }
    if _is_backend_type(vpn, "openvpn"):
        context_keys.update(
            {
                "ca_path": "ca_path_{0}".format(pk),
                "ca_contents": "ca_contents_{0}".format(pk),
                "cert_path": "cert_path_{0}".format(pk),
                "cert_contents": "cert_contents_{0}".format(pk),
                "key_path": "key_path_{0}".format(pk),
                "key_contents": "key_contents_{0}".format(pk),
            }
        )
    if _is_backend_type(vpn, "wireguard"):
        context_keys.update(
            {
                "public_key": "public_key_{}".format(pk),
                "private_key": "pvt_key_{}".format(pk),
            }
        )
    if _is_backend_type(vpn, "vxlan"):
        context_keys.update({"vni": "vni_{}".format(pk)})
    try:
        has_ip = bool(vpn.ip)
    except ObjectDoesNotExist:
        has_ip = False
    if has_ip:
        context_keys.update(
            {
                "ip_address": "ip_address_{}".format(pk),
                "vpn_subnet": "vpn_subnet_{}".format(pk),
                "server_ip_address": "server_ip_address_{}".format(pk),
                "server_ip_network": "server_ip_network_{}".format(pk),
            }
        )
    if _is_backend_type(vpn, "zerotier"):
        context_keys.update(
            {
                "node_id": "node_id_{}".format(pk),
                "network_id": "network_id_{}".format(pk),
                "network_name": "network_name_{}".format(pk),
                "zerotier_member_id": "zerotier_member_id",
                "secret": "secret",
            }
        )
    return context_keys


def _vpn_vxlan_vni(vpn):
    if _is_backend_type(vpn, "vxlan"):
        return _first_dict(_normalize_json(vpn.config).get("vxlan", [])).get("vni")


def _vpn_server_context(vpn):
    context = {}
    context_keys = _auto_context_keys(vpn)
    if vpn.host:
        context[context_keys["vpn_host"]] = vpn.host
    if _is_backend_type(vpn, "wireguard"):
        wireguard = _first_dict(_normalize_json(vpn.config).get("wireguard", []))
        if wireguard:
            context[context_keys["vpn_port"]] = wireguard.get("port")
    try:
        ca = vpn.ca
    except ObjectDoesNotExist:
        ca = None
    if ca:
        ca_filename = "ca-{0}-{1}.pem".format(ca.pk, ca.common_name.replace(" ", "_"))
        ca_path = "{0}/{1}".format(app_settings.CERT_PATH, ca_filename)
        context.update(
            {
                context_keys["ca_path"]: ca_path,
                context_keys["ca_contents"]: ca.certificate,
            }
        )
    if vpn.public_key:
        context[context_keys["public_key"]] = vpn.public_key
    try:
        ip = vpn.ip
        subnet = vpn.subnet
    except ObjectDoesNotExist:
        ip = None
        subnet = None
    if ip:
        context[context_keys["server_ip_address"]] = ip.ip_address
        context[context_keys["server_ip_network"]] = (
            f"{ip.ip_address}/{subnet.subnet.max_prefixlen}"
        )
        context[context_keys["vpn_subnet"]] = str(subnet.subnet)
    if _is_backend_type(vpn, "zerotier") and vpn.network_id:
        context[context_keys["network_name"]] = vpn.name
        context[context_keys["node_id"]] = vpn.node_id
        context[context_keys["network_id"]] = vpn.network_id
    return context


def _template_context(template):
    context = (
        _normalize_json(template.default_values) if template.default_values else {}
    )
    try:
        context.update(_vpn_server_context(template.vpn))
    except (ObjectDoesNotExist, AttributeError):
        pass
    context.update(app_settings.CONTEXT.copy())
    return context


def _config_context(config):
    context = app_settings.CONTEXT.copy()
    ordered_context = OrderedDict()
    try:
        device = config.device
    except ObjectDoesNotExist:
        device = None
    if device:
        ordered_context.update(
            [
                ("name", device.name),
                ("mac_address", device.mac_address),
                ("id", str(device.id)),
                ("key", device.key),
            ]
        )
        try:
            context.update(_normalize_json(device.organization.config_settings.context))
        except (ObjectDoesNotExist, AttributeError):
            pass
        try:
            if device.group:
                context.update(_normalize_json(device.group.context))
        except (ObjectDoesNotExist, AttributeError):
            pass
        context.update(_vpn_context(config))
        if app_settings.HARDWARE_ID_ENABLED:
            context.update({"hardware_id": str(device.hardware_id)})
    if config.context:
        context.update(_normalize_json(config.context))
    ordered_context.update(sorted(context.items()))
    return ordered_context


def _vpn_context(config):
    context = {}
    for vpnclient in config.vpnclient_set.all():
        vpn = vpnclient.vpn
        vpn_id = _pk_hex(vpn)
        context.update(_vpn_server_context(vpn))
        vpn_context_keys = _auto_context_keys(vpn)
        try:
            cert = vpnclient.cert
        except ObjectDoesNotExist:
            cert = None
        if cert:
            cert_filename = "client-{0}.pem".format(vpn_id)
            cert_path = "{0}/{1}".format(app_settings.CERT_PATH, cert_filename)
            key_filename = "key-{0}.pem".format(vpn_id)
            key_path = "{0}/{1}".format(app_settings.CERT_PATH, key_filename)
            context.update(
                {
                    vpn_context_keys["cert_path"]: cert_path,
                    vpn_context_keys["cert_contents"]: cert.certificate,
                    vpn_context_keys["key_path"]: key_path,
                    vpn_context_keys["key_contents"]: cert.private_key,
                }
            )
        if vpnclient.public_key:
            context[f"pub_key_{vpn_id}"] = vpnclient.public_key
        if vpnclient.private_key:
            context[f"pvt_key_{vpn_id}"] = vpnclient.private_key
        try:
            has_subnet = bool(vpn.subnet)
            ip = vpnclient.ip
        except ObjectDoesNotExist:
            has_subnet = False
            ip = None
        if has_subnet and ip:
            context[vpn_context_keys["ip_address"]] = ip.ip_address
        vni = _vpn_vxlan_vni(vpn)
        if "vni" in vpn_context_keys and (vpnclient.vni or vni):
            context[vpn_context_keys["vni"]] = f"{vpnclient.vni or vni}"
        if vpnclient.secret:
            context[vpn_context_keys["zerotier_member_id"]] = (
                vpnclient.zerotier_member_id
            )
            context[vpn_context_keys["secret"]] = vpnclient.secret
    return context


def _remove_duplicated_files(backend_instance):
    if "files" not in backend_instance.config:
        return
    unique_files = []
    for file in backend_instance.config["files"]:
        if file not in unique_files:
            unique_files.append(file)
    backend_instance.config["files"] = unique_files


def _checksum(config):
    backend = import_string(config.backend)
    templates = []
    context = {}
    for template in config.templates.all():
        templates.append(_normalize_json(template.config))
        context.update(_template_context(template))
    config_data = _normalize_json(config.config)
    try:
        device = config.device
    except ObjectDoesNotExist:
        device = None
    if device and "hostname" not in config_data.get("general", {}):
        config_data = deepcopy(config_data)
        config_data.setdefault("general", {})
        config_data["general"]["hostname"] = device.name.replace(":", "-")
    context.update(_config_context(config))
    backend_instance = backend(
        config=config_data,
        templates=templates,
        context=context,
    )
    if templates:
        _remove_duplicated_files(backend_instance)
    return hashlib.md5(backend_instance.generate().getvalue()).hexdigest()


def populate_checksum_db(apps, schema_editor):
    """
    Populate checksum_db field with current checksum values
    for existing Config objects.

    We don't want to change the Config.status when populating this field,
    hence we use Config.objects.bulk_update() instead of
    Config.update_status_if_checksum_changed().
    """
    Config = apps.get_model("config", "Config")
    VpnClient = apps.get_model("config", "VpnClient")
    chunk_size = 100
    updated_configs = []
    qs = (
        Config.objects.prefetch_related(
            Prefetch(
                "vpnclient_set",
                queryset=VpnClient.objects.select_related("vpn", "cert", "ip"),
            ),
            "templates",
        )
        .select_related(
            "device", "device__group", "device__organization__config_settings"
        )
        .filter(checksum_db__isnull=True)
        .iterator(chunk_size=chunk_size)
    )
    for config in qs:
        config.checksum_db = _checksum(config)
        updated_configs.append(config)
        if len(updated_configs) >= chunk_size:
            Config.objects.bulk_update(updated_configs, ["checksum_db"])
            updated_configs = []

    if updated_configs:
        Config.objects.bulk_update(updated_configs, ["checksum_db"])


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0060_cleanup_api_task_notification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="checksum_db",
            field=models.CharField(
                blank=True,
                help_text=("Checksum of the generated configuration."),
                max_length=32,
                null=True,
                verbose_name="configuration checksum",
            ),
        ),
        migrations.RunPython(
            populate_checksum_db,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
