# Generated by Django for issue #1113 optimization

from django.db import migrations, models


def populate_checksum_db(apps, schema_editor):
    """
    Populate checksum_db field with current checksum values
    for existing Config objects.

    We don't want to change the Config.status when populating this field,
    hence we use Config.objects.bulk_update() instead of
    Config.update_status_if_checksum_changed().
    """
    Config = apps.get_model("config", "Config")
    chunk_size = 100
    updated_configs = []
    qs = (
        Config.objects.prefetch_related("vpnclient_set", "templates")
        .select_related("device", "device__organization__config_settings")
        .filter(checksum_db__isnull=True)
        .iterator(chunk_size=chunk_size)
    )
    for config in qs:
        config.checksum_db = config.checksum
        updated_configs.append(config)
        if len(updated_configs) >= chunk_size:
            Config.objects.bulk_update(updated_configs, ["checksum_db"])
            updated_configs = []

    if updated_configs:
        Config.objects.bulk_update(updated_configs, ["checksum_db"])


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0060_cleanup_api_task_notification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="checksum_db",
            field=models.CharField(
                blank=True,
                help_text=("Checksum of the generated configuration."),
                max_length=32,
                null=True,
                verbose_name="configuration checksum",
            ),
        ),
        migrations.RunPython(
            populate_checksum_db,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
