# Generated by Django 5.2.1 on 2025-06-17 16:51

from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0060_whoisinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whoisinfo",
            name="country",
        ),
        migrations.RemoveField(
            model_name="whoisinfo",
            name="organization_name",
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="isp",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Organization associated with registered "
                    "Autonomous System Number"
                ),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="organizationconfigsettings",
            name="who_is_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text="Whether the WhoIs lookup feature is enabled",
                null=True,
                verbose_name="WhoIs Enabled",
            ),
        ),
    ]
