# Generated by Django 5.2.1 on 2025-06-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_remove_whoisinfo_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationconfigsettings",
            old_name="who_is_enabled",
            new_name="whois_enabled",
        ),
    ]
