# Generated by Django 5.2.11 on 2026-03-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_config_checksum_db"),
        migrations.swappable_dependency(settings.DJANGO_X509_CA_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="ca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.DJANGO_X509_CA_MODEL,
                verbose_name="Certification Authority",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
