# Generated by Django 5.2.1 on 2025-07-10 18:09

from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0061_whoisinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="approximate_location_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text="Whether the approximate location feature is enabled",
                null=True,
                verbose_name="Approximate Location Enabled",
            ),
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="latitude",
            field=models.FloatField(blank=True, help_text="Latitude", null=True),
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="longitude",
            field=models.FloatField(blank=True, help_text="Longitude", null=True),
        ),
    ]
