# Generated by Django 5.2.9 on 2025-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_config_checksum_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
        migrations.AlterField(
            model_name='config',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Additional <a href="http://netjsonconfig.openwisp.org/en/stable/general/basics.html#context" target="_blank">context (configuration variables)</a> in JSON format'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='This field can be used to add meta data for the group or to add "Configuration Variables" to the devices.', verbose_name='Configuration Variables'),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Group meta data, use this field to store data which is related to this group and can be retrieved via the REST API.', verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='organizationconfigsettings',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='This field can be used to add "Configuration Variables" to the devices.', verbose_name='Configuration Variables'),
        ),
        migrations.AlterField(
            model_name='template',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
        migrations.AlterField(
            model_name='template',
            name='default_values',
            field=models.JSONField(blank=True, default=dict, help_text='A dictionary containing the default values for the variables used by this template; these default variables will be used during schema validation.', verbose_name='Default Values'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='config',
            field=models.JSONField(default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
    ]
