# Generated by Django for issue #1113 optimization

from django.db import migrations, models
from swapper import load_model


def populate_checksum_db(apps, schema_editor):
    """
    Populate checksum_db field with current checksum values
    for existing Config objects.
    """
    Config = load_model("config", "Config")
    qs = (
        Config.objects.prefetch_related("vpnclient_set", "templates")
        .select_related("device", "device__organization__config_settings")
        .filter(checksum_db__isnull=True)
        .iterator(chunk_size=100)
    )
    for config in qs:
        config.update_status_if_checksum_changed()


class Migration(migrations.Migration):
    dependencies = [
        (
            "config",
            "0062_organizationconfigsettings_approximate_location_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="checksum_db",
            field=models.CharField(
                blank=True,
                help_text=("Checksum of the generated configuration."),
                max_length=32,
                null=True,
                verbose_name="configuration checksum",
            ),
        ),
        migrations.RunPython(
            populate_checksum_db,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
