# Generated by Django for issue #1113 optimization

from django.db import migrations, models


def populate_checksum_db(apps, schema_editor):
    """
    Populate checksum_db field with current checksum values
    for existing Config objects.
    """
    Config = apps.get_model("config", "Config")
    batch = []
    batch_size = 500
    qs = Config.objects.filter(checksum_db__isnull=True).iterator()
    for config in qs:
        config.checksum_db = config.checksum
        batch.append(config)
        if len(batch) >= batch_size:
            Config.objects.bulk_update(batch, ["checksum_db"])
            batch = []
    if batch:
        Config.objects.bulk_update(batch, ["checksum_db"])


class Migration(migrations.Migration):
    dependencies = [
        (
            "config",
            "0062_organizationconfigsettings_approximate_location_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="checksum_db",
            field=models.CharField(
                blank=True,
                help_text=("Checksum of the generated configuration."),
                max_length=32,
                null=True,
                verbose_name="configuration checksum",
            ),
        ),
        migrations.RunPython(
            populate_checksum_db,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
