# Generated by Django 5.2.13 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0063_replace_jsonfield_with_django_builtin"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="notes",
            field=models.TextField(blank=True, help_text="internal notes"),
        ),
    ]
