# Generated by Django 5.2.12 on 2026-03-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "config",
            "0063_organizationconfigsettings_estimated_location_enabled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationconfigsettings",
            name="estimated_location_enabled",
        ),
    ]
