# Generated by Django 5.2.14 on 2026-05-26 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import openwisp_controller.config.base.template


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0063_replace_jsonfield_with_django_builtin"),
        migrations.swappable_dependency(settings.DJANGO_X509_CA_MODEL),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="blueprint_cert",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Select an unassigned certificate "
                "to copy extensions and properties from.",
                limit_choices_to={"devicecertificate__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.DJANGO_X509_CERT_MODEL,
                verbose_name="Blueprint Certificate",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="ca",
            field=models.ForeignKey(
                blank=True,
                help_text="The Certificate Authority that will sign "
                "certificates generated by this template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.DJANGO_X509_CA_MODEL,
                verbose_name="Certificate Authority",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="auto_cert",
            field=models.BooleanField(
                db_index=True,
                default=openwisp_controller.config.base.template.default_auto_cert,
                help_text="whether tunnel specific configuration "
                "(cryptographic keys, ip addresses, etc) should be "
                "automatically generated and managed behind the scenes for "
                "each configuration using this template, valid only for the "
                "VPN and certificate template types",
                verbose_name="automatic tunnel provisioning",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
