# Generated by Django 5.2.14 on 2026-05-26 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0063_replace_jsonfield_with_django_builtin"),
        migrations.swappable_dependency(settings.DJANGO_X509_CA_MODEL),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="blueprint_cert",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Select an unassigned certificate to "
                "copy extensions and properties from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.DJANGO_X509_CERT_MODEL,
                verbose_name="Blueprint Certificate",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="ca",
            field=models.ForeignKey(
                blank=True,
                help_text="The Certificate Authority that will sign "
                "certificates generated by this template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.DJANGO_X509_CA_MODEL,
                verbose_name="Certificate Authority",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
