# Generated by Django 5.2.15 on 2026-07-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0064_template_blueprint_cert_template_ca_and_more"),
        ("config", "0064_template_notes"),
    ]

    operations = []
