# Generated by Django 5.2.14 on 2026-05-27 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0064_template_blueprint_cert_template_ca_and_more"),
        migrations.swappable_dependency(settings.DJANGO_X509_CERT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_cert", models.BooleanField(default=False)),
                (
                    "cert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.DJANGO_X509_CERT_MODEL,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.CONFIG_CONFIG_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.CONFIG_TEMPLATE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device certificate",
                "verbose_name_plural": "Device certificates",
                "abstract": False,
                "swappable": "CONFIG_DEVICECERTIFICATE_MODEL",
                "unique_together": {("config", "template")},
            },
        ),
        migrations.AddField(
            model_name="config",
            name="device_certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="config_device_certificates",
                through="config.DeviceCertificate",
                to=settings.CONFIG_TEMPLATE_MODEL,
                verbose_name="device certificates",
            ),
        ),
    ]
