# Generated by Django 5.2.13 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config", "0064_template_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="whoisinfo",
            name="unreferenced_since",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
