#!/bin/bash

set -e

# JSLint check
jslint openwisp_controller/pki/static/pki/js/*.js

openwisp-qa-check \
  --migrations-to-ignore "12 0 0 4" \
  --migration-path "./openwisp_controller/config/migrations
                  ./openwisp_controller/connection/migrations
                  ./openwisp_controller/geo/migrations
                  ./openwisp_controller/pki/migrations"

echo ''
echo 'Running checks for SAMPLE_APP'
SAMPLE_APP=1 openwisp-qa-check \
  --skip-isort \
  --skip-flake8 \
  --skip-black \
  --skip-checkmigrations \
  --skip-checkendline \
  --skip-checkcommit \
  --migration-path "./tests/openwisp2/sample_config/migrations/
                    ./tests/openwisp2/sample_pki/migrations/
                    ./tests/openwisp2/sample_connection/migrations/
                    ./tests/openwisp2/sample_geo/migrations/"
