# Generated by Django 3.2.16 on 2023-01-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_default_groups_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelocation',
            name='floorplan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.GEO_FLOORPLAN_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.GEO_LOCATION_MODEL,
            ),
        ),
    ]
