# Generated by Django 5.2.1 on 2025-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_alter_devicelocation_floorplan_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="fuzzy",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, the location is considered fuzzy and "
                    "may not have precise coordinates."
                ),
            ),
        ),
    ]
