# Generated by Django 5.2.12 on 2026-03-23 14:59

import django.db.models.deletion
import swapper
from django.db import migrations, models

import openwisp_utils.fields

from .. import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_location_is_estimated"),
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationGeoSettings",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="geo_settings",
                        serialize=False,
                        to=swapper.get_model_name("openwisp_users", "Organization"),
                        verbose_name="organization",
                    ),
                ),
                (
                    "estimated_location_enabled",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=app_settings.ESTIMATED_LOCATION_ENABLED,
                        help_text="Whether the estimated location feature is enabled",
                        null=True,
                        verbose_name="Estimated Location Enabled",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic settings",
                "verbose_name_plural": "Geographic settings",
                "abstract": False,
                "swappable": swapper.swappable_setting(
                    "geo", "OrganizationGeoSettings"
                ),
            },
        ),
    ]
