# Generated by Django 5.2.12 on 2026-03-23 14:59

from django.db import migrations

from . import assign_geo_settings_permissions_to_groups


def create_geo_settings_for_existing_orgs(apps, schema_editor):
    """
    Create OrganizationGeoSettings for all existing organizations
    that don't have one yet.
    """
    Organization = apps.get_model("openwisp_users", "Organization")
    OrganizationGeoSettings = apps.get_model("geo", "OrganizationGeoSettings")

    for org in Organization.objects.all():
        OrganizationGeoSettings.objects.get_or_create(organization_id=org.pk)


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_organizationgeosettings"),
        ("openwisp_users", "0021_rename_user_id_email_openwisp_us_id_06c07a_idx"),
    ]

    operations = [
        migrations.RunPython(
            assign_geo_settings_permissions_to_groups,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_geo_settings_for_existing_orgs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
