# Generated by Django 5.2.13 on 2026-05-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sample_users", "0004_default_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expiration_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "If set, the account will be deactivated after this date passes "
                    "and the user will no longer be able to log in."
                ),
                null=True,
                verbose_name="expiration date",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "expiration_date"], name="user_active_expiry_idx"
            ),
        ),
    ]
