# Generated by Django 5.2.16 on 2026-07-29 19:17

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class Migration(migrations.Migration):

    dependencies = [
        ("sample_users", "0005_user_expiration_date_user_user_active_expiry_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_based_token",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text=_(
                    "Indicates whether the last authentication token was"
                    " obtained using the local password. When false, the"
                    " token came from an external method (eg: SSO, SAML)"
                    " and password expiration is not enforced for it. None"
                    " means no token has been issued for this user since"
                    " this feature was introduced."
                ),
                null=True,
                verbose_name=_("password based token"),
            ),
        ),
    ]
