# Generated by Django 3.1.2 on 2020-10-08 11:06

from django.db import migrations

from openwisp_controller.config import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [
        ('sample_config', '0002_default_groups_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={
                'verbose_name': app_settings.DEVICE_VERBOSE_NAME[0],
                'verbose_name_plural': app_settings.DEVICE_VERBOSE_NAME[1],
            },
        ),
    ]
