# Generated by Django 3.1.8 on 2021-05-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_users', '0002_default_groups_and_permissions'),
        ('sample_config', '0003_name_unique_per_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={
                ('mac_address', 'organization'),
                ('hardware_id', 'organization'),
            },
        ),
    ]
