# Generated by Django 3.2.15 on 2022-09-16 11:45


from django.db import migrations

from openwisp_controller.config.migrations import populate_organization_allowed_device


class Migration(migrations.Migration):
    dependencies = [
        ('sample_config', '0004_devicegroup_templates'),
    ]

    operations = [
        migrations.RunPython(
            populate_organization_allowed_device, migrations.RunPython.noop
        )
    ]
