# Generated by Django 4.2.10 on 2024-03-01 16:37

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample_config", "0005_add_organizationalloweddevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="_is_deactivated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="config",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("modified", "modified"),
                    ("applied", "applied"),
                    ("error", "error"),
                    ("deactivating", "deactivating"),
                    ("deactivated", "deactivated"),
                ],
                default="modified",
                help_text=(
                    '"modified" means the configuration is not applied yet;'
                    ' \n"applied" means the configuration is applied successfully;'
                    ' \n"error" means the configuration caused issues and it was'
                    ' rolled back;'
                ),
                max_length=100,
                no_check_for_status=True,
                verbose_name="configuration status",
            ),
        ),
    ]
