# Generated by Django 5.2.1 on 2025-06-26 17:48

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0007_alter_config_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WHOISInfo",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "isp",
                    models.CharField(
                        blank=True, help_text="Organization for ASN", max_length=100
                    ),
                ),
                ("asn", models.CharField(blank=True, help_text="ASN", max_length=10)),
                (
                    "timezone",
                    models.CharField(blank=True, help_text="Time zone", max_length=35),
                ),
                (
                    "address",
                    models.JSONField(blank=True, default=dict, help_text="Address"),
                ),
                ("cidr", models.CharField(blank=True, help_text="CIDR", max_length=49)),
                ("details", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "abstract": False,
                "swappable": "CONFIG_WHOISINFO_MODEL",
            },
        ),
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="whois_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text="Whether the WHOIS lookup feature is enabled",
                null=True,
                verbose_name="WHOIS Enabled",
            ),
        ),
    ]
