# Generated by Django 5.2.1 on 2025-07-11 16:28

import django.core.validators
from django.db import migrations, models

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0008_whoisinfo_organizationconfigsettings_whois_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="estimated_location_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text="Whether the estimated location feature is enabled",
                null=True,
                verbose_name="Estimated Location Enabled",
            ),
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
    ]
