# Generated by Django 5.2.1 on 2025-07-11 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0008_whoisinfo_organizationconfigsettings_whois_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationconfigsettings",
            name="estimated_location_enabled",
            field=openwisp_utils.fields.FallbackBooleanChoiceField(
                blank=True,
                default=None,
                fallback=False,
                help_text="Whether the estimated location feature is enabled",
                null=True,
                verbose_name="Estimated Location Enabled",
            ),
        ),
        migrations.AddField(
            model_name="whoisinfo",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, help_text="Coordinates", null=True, srid=4326
            ),
        ),
    ]
