# Generated by Django 5.2.14 on 2026-05-29 20:18

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import openwisp_controller.config.base.template


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0009_replace_jsonfield_with_django_builtin"),
        ("sample_pki", "0004_alter_ca_extensions_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="blueprint_cert",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Select an unassigned certificate "
                "to copy extensions and properties from.",
                limit_choices_to=openwisp_controller.config.base.template.AbstractTemplate.get_unassigned_certs,  # noqa
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample_pki.cert",
                verbose_name="Blueprint Certificate",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="ca",
            field=models.ForeignKey(
                blank=True,
                help_text="The Certificate Authority that will sign "
                "certificates generated by this template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sample_pki.ca",
                verbose_name="Certificate Authority",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="auto_cert",
            field=models.BooleanField(
                db_index=True,
                default=openwisp_controller.config.base.template.default_auto_cert,
                help_text="whether tunnel specific configuration "
                "(cryptographic keys, ip addresses, etc) should be "
                "automatically generated and managed behind the scenes for "
                "each configuration using this template, valid only for the "
                "VPN and certificate template types",
                verbose_name="automatic tunnel provisioning",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="DeviceCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("auto_cert", models.BooleanField(default=False)),
                ("details", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "cert",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_pki.cert",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_config.config",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_config.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device certificate",
                "verbose_name_plural": "Device certificates",
                "abstract": False,
                "unique_together": {("config", "template")},
            },
        ),
        migrations.AddField(
            model_name="config",
            name="device_certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="config_device_certificates",
                through="sample_config.DeviceCertificate",
                to="sample_config.template",
                verbose_name="device certificates",
            ),
        ),
    ]
