# Generated by Django 5.2.14 on 2026-05-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0009_replace_jsonfield_with_django_builtin"),
        ("sample_pki", "0004_alter_ca_extensions_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="blueprint_cert",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Select an unassigned certificate to copy "
                "extensions and properties from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sample_pki.cert",
                verbose_name="Blueprint Certificate",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="ca",
            field=models.ForeignKey(
                blank=True,
                help_text="The Certificate Authority that will sign certificates "
                "generated by this template.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sample_pki.ca",
                verbose_name="Certificate Authority",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
