# Generated by Django 5.2.12 on 2026-04-02 07:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sample_config",
            "0009_organizationconfigsettings_approximate_location_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="configuration in NetJSON DeviceConfiguration format",
                verbose_name="configuration",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "allows overriding "
                    '<a href="https://openwisp.io/docs/stable/controller/'
                    'user/variables.html" target="_blank">'
                    "configuration variables</a>"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="devicegroup",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Define configuration variables available "
                    "to all devices in this group"
                ),
                verbose_name="Configuration Variables",
            ),
        ),
        migrations.AlterField(
            model_name="devicegroup",
            name="meta_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Store custom metadata related to this group. "
                    "This field is intended for arbitrary data that "
                    "does not affect device configuration and can be "
                    "retrieved via the REST API for integrations or "
                    "external tools."
                ),
                verbose_name="Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="organizationconfigsettings",
            name="context",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Define reusable configuration variables "
                    "available to all devices in this organization"
                ),
                verbose_name="Configuration Variables",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="configuration in NetJSON DeviceConfiguration format",
                verbose_name="configuration",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="default_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "Define default values for the variables used "
                    "in this template. These values are used during "
                    "validation and when a variable is not provided "
                    "by the device, group, or organization."
                ),
                verbose_name="Default Values",
            ),
        ),
        migrations.AlterField(
            model_name="vpn",
            name="config",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="configuration in NetJSON DeviceConfiguration format",
                verbose_name="configuration",
            ),
        ),
    ]
