# Generated by Django 5.2.14 on 2026-05-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0010_template_blueprint_cert_template_ca_and_more"),
        ("sample_pki", "0004_alter_ca_extensions_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auto_cert", models.BooleanField(default=False)),
                ("details", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "cert",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_pki.cert",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_config.config",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_config.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device certificate",
                "verbose_name_plural": "Device certificates",
                "abstract": False,
                "unique_together": {("config", "template")},
            },
        ),
        migrations.AddField(
            model_name="config",
            name="device_certificates",
            field=models.ManyToManyField(
                blank=True,
                related_name="config_device_certificates",
                through="sample_config.DeviceCertificate",
                to="sample_config.template",
                verbose_name="device certificates",
            ),
        ),
    ]
