# Generated by Django 5.2.14 on 2026-07-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0010_template_blueprint_cert_template_ca_and_more"),
        ("sample_config", "0010_template_notes"),
    ]

    operations = []
