# Generated by Django 5.2.16 on 2026-07-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0011_merge_20260702_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("vpn", "VPN-client"),
                    ("cert", "Certificate generator"),
                ],
                db_index=True,
                default="generic",
                help_text="template type, determines which features are available",
                max_length=16,
                verbose_name="type",
            ),
        ),
    ]
