# Generated by Django 3.1.6 on 2021-02-11 22:55

import swapper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        swapper.dependency('openwisp_users', 'Organization'),
        ('sample_connection', '0002_default_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='credentials', unique_together={('name', 'organization')}
        ),
    ]
