# Generated by Django 5.2.15 on 2026-06-15 18:15

import uuid

import django
import django.core.serializers.json
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

from openwisp_controller import connection as connection_config
from openwisp_controller.connection.migrations import (
    assign_batchcommand_permissions_to_groups,
)


class Migration(migrations.Migration):

    dependencies = [
        ("sample_config", "0009_replace_jsonfield_with_django_builtin"),
        ("sample_connection", "0004_replace_jsonfield_with_django_builtin"),
        ("sample_geo", "0005_organizationgeosettings"),
        ("sample_users", "0005_user_expiration_date_user_user_active_expiry_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("in-progress", "in progress"),
                            ("success", "success"),
                            ("failed", "failed"),
                        ],
                        default="idle",
                        max_length=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=16,
                        choices=(
                            connection_config.commands.COMMAND_CHOICES
                            if django.VERSION < (5, 0)
                            else connection_config.commands.get_command_choices
                        ),
                    ),
                ),
                (
                    "input",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True, to="sample_config.device", verbose_name="devices"
                    ),
                ),
                (
                    "skipped_devices",
                    models.JSONField(
                        blank=True,
                        null=True,
                        default=dict,
                        verbose_name="Skipped devices",
                        help_text=(
                            "Maps device UUIDs to validation error messages for "
                            "devices that were skipped during command creation."
                        ),
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sample_config.devicegroup",
                        verbose_name="device group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sample_geo.location",
                        verbose_name="location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sample_users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch command",
                "verbose_name_plural": "Batch commands",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="command",
            name="batch_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_commands",
                to="sample_connection.batchcommand",
            ),
        ),
        migrations.RunPython(
            code=assign_batchcommand_permissions_to_groups,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
