# Generated by Django 5.2.11 on 2026-02-06 06:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0009_alter_deviceconnection_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="input",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="credentials",
            name="params",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="global connection parameters",
                verbose_name="parameters",
            ),
        ),
        migrations.AlterField(
            model_name="deviceconnection",
            name="params",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text=(
                    "local connection parameters (will override the global "
                    "parameters if specified)"
                ),
                verbose_name="parameters",
            ),
        ),
    ]
