# Generated by Django 5.2.15 on 2026-06-14 18:00

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import openwisp_controller.connection.commands
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0010_replace_jsonfield_with_django_builtin"),
        ("openwisp_users", "0022_user_expiration_date"),
        migrations.swappable_dependency(settings.CONFIG_DEVICEGROUP_MODEL),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
        migrations.swappable_dependency(settings.GEO_LOCATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("in-progress", "in progress"),
                            ("success", "completed successfully"),
                            ("failed", "completed with some failures"),
                        ],
                        default="idle",
                        max_length=12,
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=openwisp_controller.connection.commands.get_command_choices,
                        max_length=16,
                    ),
                ),
                (
                    "command_input",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("execute_all", models.BooleanField(default=False)),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.CONFIG_DEVICE_MODEL,
                        verbose_name="devices",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.CONFIG_DEVICEGROUP_MODEL,
                        verbose_name="device group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.GEO_LOCATION_MODEL,
                        verbose_name="location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openwisp_users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch command",
                "verbose_name_plural": "Batch commands",
                "abstract": False,
                "swappable": "CONNECTION_BATCHCOMMAND_MODEL",
            },
        ),
        migrations.AddField(
            model_name="command",
            name="batch_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.CONNECTION_BATCHCOMMAND_MODEL,
            ),
        ),
    ]
