# Generated by Django 5.2.15 on 2026-06-23 13:40

import uuid

import django
import django.core.serializers.json
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import openwisp_controller.connection.commands

from . import assign_batchcommand_permissions_to_groups


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0010_replace_jsonfield_with_django_builtin"),
        ("openwisp_users", "0024_apikey"),
        migrations.swappable_dependency(settings.CONFIG_DEVICEGROUP_MODEL),
        migrations.swappable_dependency(settings.CONFIG_DEVICE_MODEL),
        migrations.swappable_dependency(settings.GEO_LOCATION_MODEL),
        ("config", "0036_device_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("in-progress", "in progress"),
                            ("success", "success"),
                            ("failed", "failed"),
                        ],
                        default="idle",
                        max_length=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=(
                            openwisp_controller.connection.commands.COMMAND_CHOICES
                            if django.VERSION < (5, 0)
                            else openwisp_controller.connection.commands.get_command_choices  # noqa: E501
                        ),
                        max_length=16,
                    ),
                ),
                (
                    "input",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "skipped_devices",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text=(
                            "Maps device UUIDs to validation error messages for "
                            "devices that were skipped during command creation."
                        ),
                        null=True,
                        verbose_name="Skipped devices",
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.CONFIG_DEVICE_MODEL,
                        verbose_name="devices",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.CONFIG_DEVICEGROUP_MODEL,
                        verbose_name="device group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.GEO_LOCATION_MODEL,
                        verbose_name="location",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text=("A short label to identify this batch command."),
                        max_length=64,
                        verbose_name="label",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="notes",
                        help_text="Optional notes about this batch command.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openwisp_users.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mass command",
                "verbose_name_plural": "Mass commands",
                "abstract": False,
                "swappable": "CONNECTION_BATCHCOMMAND_MODEL",
            },
        ),
        migrations.AddField(
            model_name="command",
            name="batch_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_commands",
                to=settings.CONNECTION_BATCHCOMMAND_MODEL,
            ),
        ),
        migrations.RunPython(
            code=assign_batchcommand_permissions_to_groups,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
