# Generated by Django 5.2.15 on 2026-06-14 18:00

import uuid

import django
import django.core.serializers.json
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import swapper
from django.db import migrations, models

from openwisp_controller import connection as connection_config

from . import assign_batchcommand_permissions_to_groups


class Migration(migrations.Migration):

    dependencies = [
        ("connection", "0010_replace_jsonfield_with_django_builtin"),
        ("openwisp_users", "0022_user_expiration_date"),
        ("config", "0063_replace_jsonfield_with_django_builtin"),
        ("geo", "0006_create_geo_settings_for_existing_orgs"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "idle"),
                            ("in-progress", "in progress"),
                            ("success", "success"),
                            ("failed", "failed"),
                        ],
                        default="idle",
                        max_length=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=16,
                        choices=(
                            connection_config.commands.COMMAND_CHOICES
                            if django.VERSION < (5, 0)
                            else connection_config.commands.get_command_choices
                        ),
                    ),
                ),
                (
                    "input",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "devices",
                    models.ManyToManyField(
                        blank=True,
                        to=swapper.get_model_name("config", "Device"),
                        verbose_name="devices",
                    ),
                ),
                (
                    "skipped_devices",
                    models.JSONField(
                        blank=True,
                        null=True,
                        default=dict,
                        verbose_name="Skipped devices",
                        help_text=(
                            "Maps device UUIDs to validation error messages for "
                            "devices that were skipped during command creation."
                        ),
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=swapper.get_model_name("config", "DeviceGroup"),
                        verbose_name="device group",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=swapper.get_model_name("geo", "Location"),
                        verbose_name="location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=swapper.get_model_name("openwisp_users", "Organization"),
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch command",
                "verbose_name_plural": "Batch commands",
                "abstract": False,
                "swappable": "CONNECTION_BATCHCOMMAND_MODEL",
            },
        ),
        migrations.AddField(
            model_name="command",
            name="batch_command",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch_commands",
                to=swapper.get_model_name("connection", "BatchCommand"),
            ),
        ),
        migrations.RunPython(
            code=assign_batchcommand_permissions_to_groups,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
