# Generated by Django 4.0.2 on 2022-02-28 17:12

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki', '0010_common_name_organization_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='digest',
            field=models.CharField(
                choices=[
                    ('sha1', 'SHA1'),
                    ('sha224', 'SHA224'),
                    ('sha256', 'SHA256'),
                    ('sha384', 'SHA384'),
                    ('sha512', 'SHA512'),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text='bits',
                max_length=8,
                verbose_name='digest algorithm',
            ),
        ),
        migrations.AlterField(
            model_name='ca',
            name='key_length',
            field=models.CharField(
                choices=[
                    ('512', '512'),
                    ('1024', '1024'),
                    ('2048', '2048'),
                    ('4096', '4096'),
                ],
                default=django_x509.base.models.default_key_length,
                help_text='bits',
                max_length=6,
                verbose_name='key length',
            ),
        ),
        migrations.AlterField(
            model_name='cert',
            name='digest',
            field=models.CharField(
                choices=[
                    ('sha1', 'SHA1'),
                    ('sha224', 'SHA224'),
                    ('sha256', 'SHA256'),
                    ('sha384', 'SHA384'),
                    ('sha512', 'SHA512'),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text='bits',
                max_length=8,
                verbose_name='digest algorithm',
            ),
        ),
        migrations.AlterField(
            model_name='cert',
            name='key_length',
            field=models.CharField(
                choices=[
                    ('512', '512'),
                    ('1024', '1024'),
                    ('2048', '2048'),
                    ('4096', '4096'),
                ],
                default=django_x509.base.models.default_key_length,
                help_text='bits',
                max_length=6,
                verbose_name='key length',
            ),
        ),
    ]
