# Generated by Django 5.2.10 on 2026-02-03 12:04

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pki", "0011_disallowed_blank_key_length_or_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("256", "256 (ECDSA)"),
                    ("384", "384 (ECDSA)"),
                    ("521", "521 (ECDSA)"),
                    ("1024", "1024 (RSA)"),
                    ("2048", "2048 (RSA)"),
                    ("4096", "4096 (RSA)"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("256", "256 (ECDSA)"),
                    ("384", "384 (ECDSA)"),
                    ("521", "521 (ECDSA)"),
                    ("1024", "1024 (RSA)"),
                    ("2048", "2048 (RSA)"),
                    ("4096", "4096 (RSA)"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
    ]
