# Generated by Django 5.2.1 on 2025-07-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_geo", "0003_alter_devicelocation_floorplan_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="is_estimated",
            field=models.BooleanField(
                default=False,
                help_text="Whether the location's coordinates are estimated.",
                verbose_name="Is Estimated?",
            ),
        ),
    ]
