# Generated by Django 5.2.12 on 2026-03-24 19:45

import uuid

import django.db.models.deletion
from django.db import migrations, models
from swapper import get_model_name

import openwisp_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sample_geo", "0004_location_is_estimated"),
        ("sample_users", "0004_default_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationGeoSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estimated_location_enabled",
                    openwisp_utils.fields.FallbackBooleanChoiceField(
                        blank=True,
                        default=None,
                        fallback=False,
                        help_text="Whether the estimated location feature is enabled",
                        null=True,
                        verbose_name="Estimated Location Enabled",
                    ),
                ),
                ("details", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_settings",
                        to=get_model_name("openwisp_users", "Organization"),
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic settings",
                "verbose_name_plural": "Geographic settings",
                "abstract": False,
            },
        ),
    ]
