name: PR Issue Auto-Assignment

on:
  pull_request_target:
    types: [opened, reopened, closed]

permissions:
  contents: read
  issues: write
  pull-requests: read

concurrency:
  group: bot-autoassign-pr-link-${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OPENWISP_BOT_APP_ID }}
          private-key: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}

      - name: Checkout openwisp-utils
        uses: actions/checkout@v6
        with:
          repository: openwisp/openwisp-utils
          ref: master
          path: openwisp-utils

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -e openwisp-utils/.[github_actions]

      - name: Run issue assignment bot
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: >
          python openwisp-utils/.github/actions/bot-autoassign/__main__.py
          issue_assignment "$GITHUB_EVENT_PATH"
